-- MySQL Script generated by MySQL Workbench
-- Fri Dec 30 19:18:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema integrador_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `integrador_db` ;

-- -----------------------------------------------------
-- Schema integrador_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `integrador_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `integrador_db` ;

-- -----------------------------------------------------
-- Table `integrador_db`.`oradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador_db`.`oradores` ;

CREATE TABLE IF NOT EXISTS `integrador_db`.`oradores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `tema` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador_db`.`tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador_db`.`tickets` ;

CREATE TABLE IF NOT EXISTS `integrador_db`.`tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `categoria` INT NOT NULL,
  `total` INT NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `tickets` VALUES 
(2,'Juan','Silva',1,1,40,'Juan.silva.0270@gmail.com'),
(12,'Juan Agustin','Silva Lara',1,2,100,'juan.silva.0270@gmail.com'),
(13,'Elon','Musk',2,3,340,'Elon.M@Tesla.com'),
(14,'Bill','Gates',3,3,510,'Bill.G@Microsoft.com');

INSERT INTO `oradores` VALUES 
(1,'Mark','Zuckerberg','El impacto del metaverso en la sociedad'),
(2,'Elon','Musk','La Compra de Twitter y el impacto en sus usuarios'),
(3,'Bill','Gates','Sistemas operativos'),
(4,'Jeff','Bezos','El ascenso de Amazon'),
(5,'Phill','Spencer','La revolucion del Gaming moderno'),
(8,'Steve Jobs','Jobs','La revolucion en Tecnologia domestica');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
